--force not working
yiisoft/rbac-cycle-db pull request #45
Opened 2023-03-12 15:47 UTC by sobhan-m94

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

`php console rbac/cycle/init --force`
This does not work. Because getOption returns a null value if the option has no value.
Also, this method returns string and cannot be compared with a boolean value.

2023-03-13 07:42 UTC, samdark commented
Would you please add a line for https://github.com/yiisoft/rbac-cycle-db/blob/master/CHANGELOG.md? Thanks.

2023-03-13 09:28 UTC, arogachev commented on CHANGELOG.md
> +- Bug : rbac/cycle/init with --force flag not working
```suggestion

- Bug #43: Fix not working `--force` flag for `RbacCycleInit` console command.
```

2023-03-13 09:29 UTC, arogachev requested changes
:+1:

2023-03-13 09:31 UTC, arogachev commented
Tests are failing. Do you have time to fix them? Or I can help to fix them in a separate PR otherwise.

2023-03-13 10:16 UTC, sobhan-m94 commented
It seems the hasOption method always returns true.

2023-03-13 10:48 UTC, arogachev commented
I'll take a look a bit later. Thanks for reporting.

2023-03-14 08:56 UTC, arogachev commented
Closing in favor of #46. Again, thanks for discovering and reporting this.

2023-03-14 08:56 UTC, closed without merging